  version: "3.9"
  services:
    postgres:
      image: postgres:16
      environment:
        POSTGRES_USER: hehai
        POSTGRES_PASSWORD: hehai
        POSTGRES_DB: hehai110
      ports:
        - "5432:5432"
      volumes:
        - pgdata:/var/lib/postgresql/data
    redis:
      image: redis:7-alpine
      ports:
        - "6379:6379"
  volumes:
    pgdata:
